// SPDX-License-Identifier: MIT
// Builds the one generated file of each plugin here: a plugin is copied alone into the user's
// plugin cache, so it cannot reach ../../ts or node_modules, and the repo's dist/ is not committed.
//   node build.mjs           write sigelo/server.mjs and sigelo-gate/gate.mjs
//   node build.mjs --check   exit 1 if either differs from what the sources build to
// Needs `npm ci` here and in ../ts (for @noble). Output is bundled, NOT minified: the directory
// scan wants readable source. The sigelo plugin carries no wallet: the directory policy forbids
// software that transfers cryptocurrency, so the four wallet tools are cut out at build time.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..');
const check = process.argv.includes('--check');

// Exact edits to integrations/mcp/server.mjs; each must apply exactly once, or the build stops.
const EDITS = [
  [/lib\('sigelo', '\.\.\/\.\.\/ts\/dist\/sigelo\.js'\)/, "import('sigelo')"],
  [/lib\('sigelo-agent\/dist\/sigelo-agent\.js', '[^']+'\)/, "import('../../adapters/moadim/sigelo-agent.ts')"],
  [/lib\('sigelo-agent\/dist\/sigelo-agent-monero\.js', '[^']+'\)/, "import('../../adapters/moadim/sigelo-agent-monero.ts')"],
  [/const WALLET = Boolean\([^\n]*\);/, 'const WALLET = false; // plugin build: no wallet (plugins/build.mjs)'],
  [/\nif \(WALLET\) TOOLS\.push\(\n[\s\S]*?\n\);\n/, '\n'],
  [/\nasync function wallet\(argv\) \{\n[\s\S]*?\n\}\n/, '\n'],
  [/\$\{WALLET \? '[^']*' : ''\}/, ''],
  [/\n {2}sigelo_wallet_balance:[^\n]*\n {2}sigelo_wallet_receive:[^\n]*\n {2}sigelo_wallet_pay:[^\n]*\n {2}sigelo_wallet_history:[^\n]*/, ''],
];
const sigeloSrc = (name) => join(REPO, 'ts/src', `${name}.ts`);
const resolver = {
  name: 'sigelo-src',
  setup(b) {
    // The libraries' TypeScript sources stand in for their unbuilt dist/ and npm names.
    b.onResolve({ filter: /^sigelo$/ }, () => ({ path: sigeloSrc('sigelo') }));
    b.onResolve({ filter: /^sigelo\/dist\/[a-z_-]+\.js$/ }, (a) => ({ path: sigeloSrc(a.path.slice(12, -3)) }));
    b.onResolve({ filter: /\/ts\/dist\/[a-z_-]+\.js$/ }, (a) => ({ path: sigeloSrc(a.path.match(/([a-z_-]+)\.js$/)[1]) }));
    b.onLoad({ filter: /integrations\/mcp\/server\.mjs$/ }, (a) => {
      let src = readFileSync(a.path, 'utf8');
      for (const [re, to] of EDITS) {
        const n = src.split(re).length - 1;
        if (n !== 1) throw new Error(`plugins/build.mjs: edit ${re} matched ${n} times in server.mjs; update EDITS`);
        src = src.replace(re, to);
      }
      if (/sigelo_wallet_(balance|receive|pay|history)|spend\/dist|Monero wallet/.test(src)) throw new Error('plugins/build.mjs: wallet code left in the plugin build');
      return { contents: src, loader: 'js' };
    });
  },
};
const banner = (from) => `// SPDX-License-Identifier: MIT
// GENERATED by plugins/build.mjs from ${from} and the libraries it imports (ts/src,
// adapters/moadim, @noble/ed25519 and @noble/hashes, both MIT). Do not edit: edit the sources,
// then \`node plugins/build.mjs\`. Node >= 22.18, no dependencies, no network.`;
const TARGETS = [
  ['integrations/mcp/server.mjs', 'sigelo/server.mjs'],
  ['gate/claude-code/gate.mjs', 'sigelo-gate/gate.mjs'],
];
let stale = 0;
for (const [from, to] of TARGETS) {
  const r = await build({
    entryPoints: [join(REPO, from)], bundle: true, platform: 'node', format: 'esm', target: 'node22',
    absWorkingDir: REPO, write: false, plugins: [resolver], legalComments: 'inline', charset: 'utf8', logLevel: 'warning',
    banner: { js: banner(from) },
  });
  const out = r.outputFiles[0].text.replaceAll(REPO + '/', '');
  const dest = join(HERE, to);
  if (check) {
    let cur = '';
    try { cur = readFileSync(dest, 'utf8'); } catch {}
    if (cur !== out) { console.error(`stale: plugins/${to} (run node plugins/build.mjs)`); stale++; }
  } else {
    writeFileSync(dest, out);
    console.log(`plugins/${to}: ${(out.length / 1024).toFixed(0)} KiB`);
  }
}
if (stale) process.exit(1);
